import { Todo } from "./todo.model";

export const TODOS: Todo[] = [
    { id: 1, title: 'Install Angular CLI', completed: true },
    { id: 2, title: 'Create new app', completed: true },
    { id: 3, title: 'Serve app', completed: true },
    { id: 4, title: 'Develop app', completed: false },
    { id: 5, title: 'Deploy app', completed: false },
    { id: 6, title: 'Maintain app', completed: false },
    { id: 7, title: 'Update app', completed: false },
    { id: 8, title: 'Delete app', completed: false },
    { id: 9, title: 'Install Angular CLI', completed: true },
    { id: 10, title: 'Create new app', completed: true },
    { id: 11, title: 'Serve app', completed: true },
    { id: 12, title: 'Develop app', completed: false },
    { id: 13, title: 'Deploy app', completed: false },
    { id: 14, title: 'Maintain app', completed: false },
    { id: 15, title: 'Update app', completed: false },
    { id: 16, title: 'Delete app', completed: false },
    { id: 17, title: 'Install Angular CLI', completed: true },
    { id: 18, title: 'Create new app', completed: true },
    { id: 19, title: 'Serve app', completed: true },
    { id: 20, title: 'Develop app', completed: false },
    { id: 21, title: 'Deploy app', completed: false },
    { id: 22, title: 'Maintain app', completed: false },
    { id: 23, title: 'Update app', completed: false },
    { id: 24, title: 'Delete app', completed: false },
    { id: 25, title: 'Install Angular CLI', completed: true },
    { id: 26, title: 'Create new app', completed: true },
    { id: 27, title: 'Serve app', completed: true },
    { id: 28, title: 'Develop app', completed: false },
    { id: 29, title: 'Deploy app', completed: false },
    { id: 30, title: 'Maintain app', completed: false },
    { id: 31, title: 'Update app', completed: false },
    { id: 32, title: 'Delete app', completed: false },
    { id: 33, title: 'Install Angular CLI', completed: true },
    { id: 34, title: 'Create new app', completed: true },
];
