export const Alphabet: {
    letter: string;
    value: number;
}[] = [
        { letter: '가', value: 0 },
        { letter: '나', value: 1 },
        { letter: '다', value: 2 },
        { letter: '라', value: 3 },
        { letter: '마', value: 4 },
        { letter: '바', value: 5 },
        { letter: '사', value: 6 },
        { letter: '아', value: 7 },
        { letter: '자', value: 8 },
        { letter: '차', value: 9 },
        { letter: '카', value: 10 },
        { letter: '타', value: 11 },
        { letter: '파', value: 12 },
        { letter: '하', value: 13 },
        { letter: 'A', value: 14 },
        { letter: 'B', value: 15 },
        { letter: 'C', value: 16 },
        { letter: 'D', value: 17 },
        { letter: 'E', value: 18 },
        { letter: 'F', value: 19 },
        { letter: 'G', value: 20 },
        { letter: 'H', value: 21 },
        { letter: 'I', value: 22 },
        { letter: 'J', value: 23 },
        { letter: 'K', value: 24 },
        { letter: 'L', value: 25 },
        { letter: 'M', value: 26 },
        { letter: 'N', value: 27 },
        { letter: 'O', value: 28 },
        { letter: 'P', value: 29 },
        { letter: 'Q', value: 30 },
        { letter: 'R', value: 31 },
        { letter: 'S', value: 32 },
        { letter: 'T', value: 33 },
        { letter: 'U', value: 34 },
        { letter: 'V', value: 35 },
        { letter: 'W', value: 36 },
        { letter: 'X', value: 37 },
        { letter: 'Y', value: 38 },
        { letter: 'Z', value: 39 }
    ]
